<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="BDD Webservice And UI" duration-ms="493" started-at="2018-09-18T14:18:51Z" finished-at="2018-09-18T14:18:52Z">
    <groups>
      <group name="cucumber">
        <method signature="TestNgTestRunner.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:TestRunners.TestNgTestRunner@5d5eef3d]" name="feature" class="TestRunners.TestNgTestRunner"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="All Tests" duration-ms="493" started-at="2018-09-18T14:18:51Z" finished-at="2018-09-18T14:18:52Z">
      <class name="TestRunners.TestNgTestRunner">
        <test-method status="PASS" signature="readInputData()[pri:0, instance:TestRunners.TestNgTestRunner@5d5eef3d]" name="readInputData" is-config="true" duration-ms="13" started-at="2018-09-18T19:48:51Z" finished-at="2018-09-18T19:48:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readInputData -->
        <test-method status="FAIL" signature="setUpClass()[pri:0, instance:TestRunners.TestNgTestRunner@5d5eef3d]" name="setUpClass" is-config="true" duration-ms="0" started-at="2018-09-18T19:48:51Z" finished-at="2018-09-18T19:48:51Z">
          <exception class="cucumber.runtime.DuplicateStepDefinitionException">
            <message>
              <![CDATA[Duplicate step definitions in StepDefinitions.functional.MemberDemographicSteps.verify_status_code(int) in file:/C:/Users/vmsaisumamanasa/Desktop/BDDWebserviceAndUi-Master/BDDWebserviceAndUi-master/target/classes/ and StepDefinitions.webServices.MemberRewardServiceSteps.verifyResponseStatus(int) in file:/C:/Users/vmsaisumamanasa/Desktop/BDDWebserviceAndUi-Master/BDDWebserviceAndUi-master/target/classes/]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.DuplicateStepDefinitionException: Duplicate step definitions in StepDefinitions.functional.MemberDemographicSteps.verify_status_code(int) in file:/C:/Users/vmsaisumamanasa/Desktop/BDDWebserviceAndUi-Master/BDDWebserviceAndUi-master/target/classes/ and StepDefinitions.webServices.MemberRewardServiceSteps.verifyResponseStatus(int) in file:/C:/Users/vmsaisumamanasa/Desktop/BDDWebserviceAndUi-Master/BDDWebserviceAndUi-master/target/classes/
	at cucumber.runtime.RuntimeGlue.addStepDefinition(RuntimeGlue.java:33)
	at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:151)
	at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:68)
	at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:41)
	at cucumber.runtime.java.JavaBackend.loadGlue(JavaBackend.java:86)
	at cucumber.runtime.Runtime.<init>(Runtime.java:92)
	at cucumber.runtime.Runtime.<init>(Runtime.java:70)
	at cucumber.runtime.Runtime.<init>(Runtime.java:66)
	at cucumber.api.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:42)
	at TestRunners.TestNgTestRunner.setUpClass(TestNgTestRunner.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.DuplicateStepDefinitionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="tearDownClass()[pri:0, instance:TestRunners.TestNgTestRunner@5d5eef3d]" name="tearDownClass" is-config="true" duration-ms="0" started-at="2018-09-18T19:48:52Z" finished-at="2018-09-18T19:48:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at TestRunners.TestNgTestRunner.tearDownClass(TestNgTestRunner.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
        <test-method status="SKIP" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:TestRunners.TestNgTestRunner@5d5eef3d]" name="feature" duration-ms="0" started-at="2018-09-18T19:48:52Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2018-09-18T19:48:52Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at TestRunners.TestNgTestRunner.features(TestNgTestRunner.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 16 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
      </class> <!-- TestRunners.TestNgTestRunner -->
    </test> <!-- All Tests -->
  </suite> <!-- BDD Webservice And UI -->
</testng-results>
